name: main-ci

on:
  pull_request:
    branches: [ $default-branch ]

jobs:
  ubuntu-build-18.04:
    runs-on: ubuntu-18.04

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
