name: pdebuild

on:
  pull_request:
    branches: main
  push:
    branches: main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
        include:
          - os: ubuntu-18.04
            extra_debbuildopts: '--debbuildopts "-Pros2"'
    steps:
    - uses: actions/checkout@v2
    - name: Create the build environment using pbuilder
      shell: bash
      run:  |
        sudo apt update
        sudo apt install coreutils curl sed gawk git -y
        bash .github/workflows/scripts/setup-pbuilder-env.sh
    - name: Run pdebuild
      shell: bash
      run:  |
        if [[ ${{ matrix.os }} == "ubuntu-16.04" ]]
        then
          export DEB_BUILD_PROFILES=ros1
        fi
        pdebuild
    - name: Upload the generated deb file to the bintray repository
      if: ${{ github.event_name == 'push' }}
      shell: bash
      env:
        BINTRAY_API_KEY : ${{ secrets.BINTRAY_API_KEY }}
      run:  |
        export VER=`cat ./debian/changelog | head -n1 | awk -F ['()'] {'print $2}'`
        export REL_VER=${VER}~$(date +'%Y%m%d%H%M')
        export DISTRO=`lsb_release -sc`
        export ARCH=`dpkg-architecture -q DEB_TARGET_ARCH`
        for each_deb in $(ls /var/cache/pbuilder/result/nnstreamer-ros*_${VER}_${ARCH}.deb); do
          export PKG_NAME=`basename ${each_deb} | awk -F_ '{print $1}'`_${REL_VER}_${DISTRO}_${ARCH}.deb
          curl -T "${each_deb}" -uwooksong:"${BINTRAY_API_KEY}" -H "X-Bintray-Package:nnstreamer-ros" -H "X-Bintray-Version:${REL_VER}" -H "X-Bintray-Debian-Distribution:${DISTRO}" -H "X-Bintray-Debian-Component:main" -H "X-Bintray-Debian-Architecture:${ARCH}" -H "X-Bintray-Publish:1" https://api.bintray.com/content/nnsuite/nnstreamer-ros/pool/main/m/${PKG_NAME}
        done
